server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${StockControlAuthDb}
    username: ${UsernamePostgres}
    password: ${PasswordPostgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true